{% set version = "0.8.12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-phylobase
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/phylobase_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/phylobase/phylobase_{{ version }}.tar.gz
  sha256: 9b81ca60dc6215e74b720880cc2db3abc1f7e6d8785ea7d7df95a950f0778f20

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rnexml                     # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-ade4                       # [build_platform != target_platform]
    - r-ape                        # [build_platform != target_platform]
    - r-rncl                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rnexml
    - r-rcpp >=0.11.0
    - r-ade4
    - r-ape >=3.0
    - r-rncl >=0.6.0
  run:
    - r-base
    - r-rnexml
    - r-rcpp >=0.11.0
    - r-ade4
    - r-ape >=3.0
    - r-rncl >=0.6.0

test:
  commands:
    - $R -e "library('phylobase')"           # [not win]
    - "\"%R%\" -e \"library('phylobase')\""  # [win]

about:
  home: https://github.com/fmichonneau/phylobase
  license: GPL-2.0-or-later
  summary: Provides a base S4 class for comparative methods, incorporating one or more trees and trait data.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
