bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: AboHFL0JKHagKVBD7bv85hfswjNAZ2qgSlzigchROtf7BXvdis/SEpXaggG7Q2eb8C1NXjXt0ny/h5ij789/sGwen53miA2EMtc1FOsZFHZdy9VSBGcDu/nSBeHM5LZ/HYNJiTugfjcQS4kRniSEGd59Ell80pdVCr0goyaXIUTTYtc4W5fehUkXsp37pyXuJuW0a33A2eeHzVRRA6PRMHwaOfELj8XQTHwCBfi4DhFf8Qoucks/f4QnOyBEJ6iTiX+3EMpyO4K7Apqie+QvhNzrKXjbtj0BfbZsPX9tqeHH/GCvdSsBTWDRTm2TDtSVnQv0lIajU4dZnmoM3muq9lWQFS7x5LYGU7HvbTa91HwAAcwJZ72lra5aaGnpyAMwWQ6wiTrbi7EqZ/jyNfMBSN2IC9P82wO+Ig11YMuZJcQU8Sn2e3RluFAAM6kBpd/oJNfeJ5tvIa08YupxR+BIxcalQ3LwycYOAlGh/WwM2Gq/Spq8DJM3BSWcfr7j9jIW1DAjNLTZ8A293p87i9eswytsAtsUGtZ5gnP+Ur/i8MC1u7oxCH1WoiKX9bh9xoys7L4AF9E6W45DPoXXEB7w0lEA9jCsToFutARbhxOXs+N2UToFB//0E2q34S5uRAwLxO8+4O6HKA0H/k1Xbk0ZjnpaF5JyAY0JfNaE7DHOFRA=
conda_forge_output_validation: true
